単語UIを追加
kufu/product-design-wiki pull request #1
Opened 2022-10-19 08:29 UTC by daxelbook

わいわい

2022-10-19 08:38 UTC, kgsi commented on src/pages/documents/ui.md
> +description: 最初のブログ記事
```suggestion
description: UIとはUser Interface（ユーザーインタフェース）の略で、物やサービスの利用者（ユーザー）とシステムをつなぐ界面（インターフェース）のこと。
```

2022-10-19 08:40 UTC, uknmr commented on src/pages/documents/ui.md
> +description: 最初のブログ記事
description って何に使われる想定ですか?

2022-10-19 08:45 UTC, uknmr requested changes

2022-10-19 08:45 UTC, uknmr commented on src/pages/documents/ui.md
> +tag: word
わからない、タグ難しい

```suggestion
tag: word, UI, GUI, CUI
```

2022-10-19 08:45 UTC, uknmr commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
プロデザの責務の一つである「円滑な開発活動のサポート」も、開発における UI としてのプロデザ、という認識があります。
期待値調整などコミュニケーションも含めた広義の UI の話がほしいと思いました!

2022-10-19 08:51 UTC, daxelbook commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
我々プロデザはUIの姿をビジネス、エンジニアリング上の制約を踏まえて可視化することで開発の他のメンバーとコミュニケーションをとっている　的な話です？

2022-10-19 13:40 UTC, uknmr commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
開発コミュニケーションも我々のデザイン対象であり、界面の一つで、つまり UI、という話です!

2022-10-19 21:34 UTC, uknmr commented on src/pages/documents/ui.md
> +description: 最初のブログ記事
meta に使われるならメンテナンス面倒なので、一段落目をまるっと description にしちゃうのどうですか?

2022-10-20 02:50 UTC, daxelbook commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
なるほど〜〜〜。
めっちゃ分かるんですが、それは”ユーザー”インターフェースではなくまた何かのインターフェースではないですか？
そこまで範囲を広げてしまうと本来一般的に伝えるべき内容がぶれてしまうので少しまだイメージついてないです！コラムとかで別途書くとかだとイメージあるんですがどうでしょう？

2022-10-20 03:12 UTC, kgsi commented on src/pages/documents/ui.md
> +description: 最初のブログ記事
意図してディスクリプションを制御したいケースがあると思うんです（例えば一行目が短すぎて意味消失なこともありえるのかなと。
例えばdescriptionはデフォルトオフで、ディスクリプションが入っていたら設定される...とかはどうですか？

2022-10-20 03:47 UTC, uknmr commented on src/pages/documents/ui.md
> +description: 最初のブログ記事
> ディスクリプションが入っていたら設定される

賛成ですー!
だいたいは1段落目で問題ない気がするので、良いデフォルトは1段落目かなと考えます。

2022-10-20 03:52 UTC, uknmr commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
プロデザの Readme にも責務として掲げているくらいなので、共通認識だと思ってたんですが違いそうなんですかね:innocent:

> 本来一般的に伝えるべき内容

汎用的な定義を伝えるというよりは、プロデザの話を書くばだと思っています。
広義の UI の話も出ているので、プロデザは何かと接する界面すべてをインターフェースとして捉えてる1文はあっても良いのかなと!

2022-10-20 06:16 UTC, daxelbook commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
いや、共通認識です！

ただ外部にも公開するものにおいて、UIという1つの言葉に多くの文脈を入れすぎて逆に分かりづらくなってしまうのではないかと心配になっています。なので開発時の界面としてのUIの振る舞い方はやはりコラムに書くのが一番伝えられると思っています。

こういうのはどうですか？UI記事には最後に
`SmartHRプロダクトデザイングループではUIを開発時のコミュニケーションにおける重要な界面として捉えている。そのことについては{コラム名}を参照されたい。`という風に1文を書いてその中にリンクを貼る　という感じです。「界面」記事を書くのであれば同じような一文を記事内に設けられそうです。

2022-10-20 07:05 UTC, uknmr commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
コラムに逃がすのよさそう!!!

2022-10-20 08:04 UTC, daxelbook commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
コラムはワイが書きます！

2022-10-21 04:56 UTC, uknmr commented on src/pages/documents/ui.md
> +SmartHRではUIの種類として最も主流なGUI（Graphical User Interface）を扱い他の記事でもそれを意味する。
> SmartHRプロダクトデザイングループではUIを開発時のコミュニケーションにおける重要な界面として捉えている。そのことについては{コラム名}を参照されたい。

これの反映を待っています!

2022-11-07 01:18 UTC, uknmr commented on src/pages/documents/ui.md
> +デジタルプロダクト領域でもCUIやZUIなどの異なる種類のUIが存在する。また、UIを細分化すると、人体の五感のそれぞれの感覚に働きかける界面に分けられ、視覚や聴覚、触覚と相互作用するものが一般的な物になる。
ZUI?

2022-11-07 01:18 UTC, uknmr commented on .node-version
> +16.12.0
紛れてる

2022-11-07 02:07 UTC, daxelbook commented on src/pages/documents/ui.md
> +デジタルプロダクト領域でもCUIやZUIなどの異なる種類のUIが存在する。また、UIを細分化すると、人体の五感のそれぞれの感覚に働きかける界面に分けられ、視覚や聴覚、触覚と相互作用するものが一般的な物になる。
Zooming User Interface ですね

2022-11-07 02:07 UTC, daxelbook commented on .node-version
> +16.12.0
pie

2022-11-07 02:16 UTC, daxelbook commented on .node-version
> +16.12.0
あれ、この場合 .gitignore に .node-versionを追加すればいいです。。。？

2022-11-07 02:22 UTC, daxelbook commented
コメント分いくつか修正しました

2022-11-07 02:27 UTC, daxelbook commented on src/pages/documents/ui.md
> +デジタルプロダクト領域でもCUIやZUIなどの異なる種類のUIが存在する。また、UIを細分化すると、人体の五感のそれぞれの感覚に働きかける界面に分けられ、視覚や聴覚、触覚と相互作用するものが一般的な物になる。
https://ja.wikipedia.org/wiki/%E3%82%BA%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0%E3%83%A6%E3%83%BC%E3%82%B6%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9

2022-11-07 03:45 UTC, uknmr commented on .node-version
> +16.12.0
`git rm` で消せた気がします!

2022-11-07 03:45 UTC, uknmr commented on src/pages/documents/ui.md
> +本来は、椅子やハンマーのも持ち手等の物理的な物、車のハンドルやカメラのボタンなどの複合的な機械も利用者と内なるシステムをつなぐ物として広義のUIとして考えられる。
```suggestion
本来は、椅子やハンマーのも持ち手等の物理的な物も、車のハンドルやカメラのボタンなどの複合的な物も、利用者と内なるシステムをつなぐ物として広義のUIだと考えられる。
```

2022-11-07 03:45 UTC, uknmr commented on src/pages/documents/ui.md
> +デジタルプロダクト領域でもCUIやZUIなどの異なる種類のUIが存在する。また、UIを細分化すると、人体の五感のそれぞれの感覚に働きかける界面に分けられ、視覚や聴覚、触覚と相互作用するものが一般的な物になる。
知らなかった!

```suggestion
デジタルプロダクト領域でもCUIやZUI（Zooming User Interface）などの異なる種類のUIが存在する。また、UIを細分化すると、人体の五感のそれぞれの感覚に働きかける界面に分けられ、視覚や聴覚、触覚と相互作用するものが一般的な物になる。
```

2022-11-07 03:45 UTC, uknmr commented on src/pages/documents/ui.md
> +UIとはUser Interface（ユーザーインタフェース）の略で、物やサービスの利用者（ユーザー）とシステムをつなぐ界面（インターフェース）のこと。システムが利用者がUIを通して行った操作に対する結果を返し、利用者はUIを通してその結果やシステムの状態を知ることが出来る。
インタフェースなのかインターフェースなのか、あるいは使い分けるのか?

2022-11-07 04:26 UTC, daxelbook commented on src/pages/documents/ui.md
> +UIとはUser Interface（ユーザーインタフェース）の略で、物やサービスの利用者（ユーザー）とシステムをつなぐ界面（インターフェース）のこと。システムが利用者がUIを通して行った操作に対する結果を返し、利用者はUIを通してその結果やシステムの状態を知ることが出来る。
pie

2022-11-07 04:28 UTC, daxelbook commented on src/pages/documents/ui.md
> +UIとはUser Interface（ユーザーインタフェース）の略で、物やサービスの利用者（ユーザー）とシステムをつなぐ界面（インターフェース）のこと。システムが利用者がUIを通して行った操作に対する結果を返し、利用者はUIを通してその結果やシステムの状態を知ることが出来る。
typoなので　インターフェース　に統一します！

2022-11-07 05:50 UTC, daxelbook commented
コメント分修正しました！

2022-11-07 06:45 UTC, uknmr approved these changes

2022-11-08 01:48 UTC, merged